### ISSUE TITLE
linux installation errors

### ISSUE THREAD

**Issue by pkrasam** [spacemeshos/smapp#552]
**Describe the bug**
```
sudo dpkg -i spacemesh_app_0.0.14_amd64.deb
[sudo] password for spacemesh:
(Reading database ... 110503 files and directories currently installed.)
Preparing to unpack spacemesh_app_0.0.14_amd64.deb ...
Unpacking spacemesh-app (0.0.14) over (0.0.14) ...
dpkg: dependency problems prevent configuration of spacemesh-app:
 spacemesh-app depends on libgtk-3-0; however:
  Package libgtk-3-0 is not installed.
 spacemesh-app depends on libnotify4; however:
  Package libnotify4 is not installed.
 spacemesh-app depends on libnss3; however:
  Package libnss3 is not installed.
 spacemesh-app depends on libxss1; however:
  Package libxss1 is not installed.
 spacemesh-app depends on libxtst6; however:
  Package libxtst6 is not installed.
 spacemesh-app depends on xdg-utils; however:
  Package xdg-utils is not installed.
 spacemesh-app depends on libatspi2.0-0; however:
  Package libatspi2.0-0 is not installed.
 spacemesh-app depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.
 spacemesh-app depends on libsecret-1-0; however:
  Package libsecret-1-0 is not installed.

dpkg: error processing package spacemesh-app (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.60ubuntu1) ...
Errors were encountered while processing:
 spacemesh-app
```

**To Reproduce**
1. `wget https://storage.googleapis.com/smapp/0.0.14/spacemesh_app_0.0.14_amd64.deb`
2. `sudo dpkg -i spacemesh_app_0.0.14_amd64.deb`

**Expected behavior**
Expecting an error free installation

**Screenshots**
see above

**Desktop (please complete the following information):**
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 4.15.0-88-generic

**Comment by avive** [comment]
Looks like there are some missing dependancies. I'm also running on U 18.04.4 and I'm not getting these errors when installing because I have these dependencies on my system. 
This may help:  run `sudo apt-get -f install` after dpkg to install the missing deps or use `gdebi`.
Please let me know here if this resolved your issue!

**Comment by pkrasam** [comment]
Thank you @avive I ran the following command (Thanks to Thanos our community member) to install the dependencies `sudo apt install --assume-yes libx11-xcb1 libasound2 x11-apps libice6 libsm6 libxaw7 libxft2 libxmu6 libxpm4 libxt6 x11-apps xbitmaps`

Now when I launch spacemesh_app i see the following errors before it goes blank
```
```

**Comment by whoabuddy** [comment]
@pkrasam This convo caught my eye as I installed the smapp on Ubuntu 20.04 LTS without any issues, and I *think* there were only two dependencies required that were fixed at the time of install. Overall, it was a very simple experience and I too used `dpkg -i` for the installation.

One thing I noticed in the instructions from Thanos was that the packages listed did not match the errors you received, so you may still be missing some dependencies. I would try running `apt-get` with each of the packages listed in that error message:

```
sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libappindicator3-1 libsecret-1-0
```

Then try to install the smapp again using `dpkg -i`. If that doesn't work, the `swrast` driver listed in the subsequent error above is related to Nvidia drivers (as far as my searches can tell), so there may be a configuration issue with the system.

Do you have any proprietary video drivers in use? What is the output from the commands below?

```
lspci -k | grep -EA3 'VGA|3D|Display'
```
and 
```
glxinfo | grep -i "vendor\|rendering"
```

Hopefully that helps!

**Comment by sudachen** [comment]
By the way... Why not use snap to install the app on Linux? I'm not sure about OSX, but for Linux, at least for Ubuntu, it's a quite standart way to install something.

**Comment by lrettig** [comment]
> By the way... Why not use snap to install the app on Linux? https://snapcraft.io/
> I'm not sure about OSX, but for Linux, at least for Ubuntu, it's a quite standard way to install something.

See #390 - I think there are (or at least there were) issues with electron packages like ours

**Comment by tal-m** [comment]
Electron does have some issues running in containers --- this also affects running in docker (at least for docker, using the `--no-sandbox` flag seems to work). 

I wouldn't recommend it for production use, but for testing you can try my [dockerized version of the app](https://github.com/spacemeshos/smapp/tree/docker-xpra)

It's been updated to use ubuntu 20.04 as base, on which installs cleanly, but you can look at the [Dockerfile](https://github.com/spacemeshos/smapp/blob/df7170b12bfa5d478620c19fd3ac68934b4844f7/Dockerfile) for a previous version to see the required dependencies for 18.04

**Comment by pkrasam** [comment]
Thank you @whoabuddy ...I ran through your suggested steps and still getting the same error.

Here the outputs for the two commands

Command:
```
lspci -k | grep -EA3 'VGA|3D|Display'
```
Output:
```
VGA compatible controller: ASPEED Technology, Inc. ASPEED Graphics Family (rev 41)
	Subsystem: ASPEED Technology, Inc. ASPEED Graphics Family
	Kernel modules: ast
Ethernet controller: Intel Corporation I210 Gigabit Network Connection (rev 03)
```
Command:
```
glxinfo | grep -i "vendor\|rendering"
```
Output:
```
-bash: glxinfo: command not found
```

**Comment by lrettig** [comment]
@pkrasam I can confirm that I've successfully installed the app on several Linux VMs without needing to install any other dependencies. It's odd that you're running into this. Are you running Ubuntu on some particular cloud host, or from some particular image, so that we can try recreating the error? Maybe we could try recreating it using one of these docker images... https://hub.docker.com/layers/ubuntu/library/ubuntu/bionic/images/sha256-672007d477b2cf0d38f04a4e9b8ce09cc6710172256a63be35f9fd57ccf1575b?context=explore

**Comment by whoabuddy** [comment]
The ASPEED driver from Intel is related to a specific server board, so I would guess that this is a hosted VM.

![2020-06-23 10 55 22 downloadcenter intel com 77ebd89ba0e8](https://user-images.githubusercontent.com/9038904/85448241-5915d880-b54b-11ea-8158-54e9caf0213c.png)

That might explain some of the dependency issues.

**Comment by avive** [comment]
Is there any actionable task that should be drafted to resolve this issue in the code base? I'd like to close this issue if there is none. We currently provide Ubuntu 18.04 and 20.04 deb packages which I think should be satisfactory. It is hard for a small team to provide packaging support for a larger number of linux configurations.

**Comment by IlyaVi** [comment]
Most of linux users are satisfied with the builds we provide so I'm closing this

**Comment by lrettig** [comment]
I've been using the 20.04 deb packages for the past few releases with no
problems on debian or ubuntu

>
